name: 'Update site'
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: self-hosted
    steps:
      # Runs a single command using the runners shell
      - name: Sync web server contents
        run: bash $GITHUB_WORKSPACE/sync.sh
