name: 'Update site'
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Sync web server contents
        run: git pull --rebase
